ARG ROS_DISTRO=humble 
FROM ros:${ROS_DISTRO}-ros-base 

# install dependencies package 

RUN apt-get update && apt-get install -y --no-install-recommends ros-$ROS_DISTRO-foxglove-bridge 
EXPOSE 8765 

WORKDIR / 

# Setup workspace 

# Build 
SHELL ["/bin/bash","-c"] 

# launch ros package 
CMD ["ros2", "launch", "foxglove_bridge", "foxglove_bridge_launch.xml"]